### ISSUE TITLE
API creation of message

### ISSUE THREAD

**Issue by JeanJoeris** [susiirwin/acquire_a_hire#37]
Given a job exists
I send the message data to '/api/v1/job/:job_id/new_message'
And receive a status code 200 if it successfully sent

**Comment by jmejia** [comment]
@JeanJoeris @susiirwin @brendandillon @rdavid1099 Let's make this API endpoint more RESTful.

Something like this:

```
Given a job exists
And my API key is connected to my user
And my user has permission to comment on this job
And I send a POST request to '/api/v1/jobs/:job_id/messages/' with data "{api_key: SOME_KEY, message:  SOME_MESSAGE}"
And receive a status code 201 if it successfully sent
```

**Comment by JeanJoeris** [comment]
While @rdavid1099 is working our api keys, hard code in an expected api_key

**Comment by JeanJoeris** [comment]
@jmejia - We were thinking about the problem of a requester sending a message through this end point. how will it know what professional it is sending the message to? We didn't want to pass IDs directly through the post request, that felt insecure (is it?)

Here is our solution "{api_key: SOME_KEY, message:  SOME_MESSAGE, business_name: SOME_PERCENT_ENCODED_BUSINESS_NAME}". business_name will be an optional param that requesters pass when messaging professionals. Professionals do not need this param, as the requester id is inferred from the job_id, and the professional id is inferred from the api_key

**Comment by jmejia** [comment]
@JeanJoeris Great question. This was a slight oversight on my end. You are correct, this isn't ideal from a security standpoint.

I think the ultimate goal would be to send over a unique identifier token obtained via OAuth but that is outside the scope of this story. Let's just send a `sender_id` to keep it simple. I'd like to avoid getting too specific (i.e. `requester_id` and `business_id`). If you need to send something additional over to determine which role they have in the conversation, maybe add `sender_type`.

Ideal approach for this story:
`{api_key: SOME_KEY, message: SOME_MESSAGE, sender_id: SOME_ID}`

If that's not enough to find the requester or business then:

`{api_key: SOME_KEY, message: SOME_MESSAGE, sender_id: SOME_ID, sender_type: "Business"}`

Ideally the value for sender type would be the name of a class or value in a column so you can avoid nasty `if` statements. Avoiding the `if` statement will make it easier to expand this code as we increase security later on. Example: 

``` ruby
params[:sender_type].constantize.find(params[:sender_id])

# or...
User.where(role: params[:sender_type]).find(params[:sender_id])

# instead of:
if params[:sender_type] == "Business"
  Business.find(params[:sender_id])
else params[:sender_type] == "Requester"
  Requester.find(params[:sender_id])
end
```

**Comment by JeanJoeris** [comment]
I'm leaving this card open so we can refactor towards what Josh suggested
