### ISSUE TITLE
GET /api/v1/:job_id/messages

### ISSUE THREAD

**Issue by jmejia** [susiirwin/acquire_a_hire#43]
Given a job exists
And my API key is connected to my user
And my user has permission to comment on this job
And the job has 3 messages (2 from the contractor, 1 from requester)
When I send a GET request to '/api/v1/jobs/:job_id/messages/' with data "{api_key: SOME_KEY}"
Then I should receive a status code 200
And I should see a JSON response with an array of JavaScript objects
And each object should have a poster_id, body, and created_at

**Comment by jmejia** [comment]
JSON Response should look something like this:

```
[
  {"poster_id":"1","body":"Build all the things.","created_at":"2016-10-21T15:07:42.265-06:00"},
  {"poster_id":"2","body":"OK. Give me all your money.","created_at":"2016-11-21T15:07:42.265-06:00"},
  {"poster_id":"1","body":"K thx bye.","created_at":"2016-12-21T15:07:42.265-06:00"},
]
```

**Comment by JeanJoeris** [comment]
the array of response messages should be sorted by increasing created_at
