### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by JeanJoeris** [susiirwin/acquire_a_hire#47]
As a user
when I visit "/api/api_key"
I expect to see my api key

**Comment by JeanJoeris** [comment]
I'm not totally sure what the right endpoint for this is. @jmejia - any input?

**Comment by jmejia** [comment]
@JeanJoeris Not sure if you've implemented registering yet... if not maybe something like `/api/accounts/new` with a POST sent to `/api/accounts` when the form is submitted. Viewing your api key could be `/api/accounts/:api_key` or `/api/accounts/dashboard`.

**Comment by JeanJoeris** [comment]
I think we'll go with `/api/accounts/new`, post to `/api/accounts` and view the key with `/api/accounts/dashboard`

**Comment by rdavid1099** [comment]
Awesome!
